### ISSUE TITLE
TexLive package missing `bibi.sty`

### ISSUE THREAD

**Issue by PhillRob** [rstudio/shiny#1749]
Rendering PDF using `xelatex`with arabic and latin strings does return a package not found error when deployed to shinyapps.io but works locally on mac IOS10. 
```! LaTeX Error: File `bidi.sty' not found.```
Are TexLIve packages missing on the free plan of shinyapps or is this a issue from the polyglossa package?

Can I get a list of installed packages installed on shinyapps.io or how do I to influence which xelatex packages are avail. on shinyapp.io?

Below the rmarkdown YAML header that provokes the error: 
```yaml
---
header-includes:
- \usepackage{polyglossia}
- \usepackage{fontspec}
- \usepackage{fancyhdr}
- \usepackage{bidi}
- \setmainlanguage{arabic}
- \newfontfamily{\arabicfont}{Myriad Arabic}
- \usepackage{graphicx}
- \pagestyle{fancy}
- \setlength\headheight{28pt}
- \fancyhead[L,CE]{\includegraphics[width=1cm]{AMN-logo.png}}
- \fancyfoot[L,CE]{`r format(Sys.time(), '%d %B %Y')`}
output: 
    pdf_document:
      highlight: tango
      keep_tex: yes
      latex_engine: xelatex
classoption: article
papersize: A4
fontsize: 10pt
geometry: margin=0.9in
linestretch: 1.15
---
```
```r
sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan 10.11.6

locale:
[1] en_IE.UTF-8/en_IE.UTF-8/en_IE.UTF-8/C/en_IE.UTF-8/en_IE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] rmarkdown_1.4     DT_0.2           
[3] dplyr_0.5.0       data.table_1.10.4
[5] jsonlite_1.4      httr_1.2.1       
[7] shiny_1.0.1      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10     knitr_1.15.1    
 [3] magrittr_1.5     xtable_1.8-2    
 [5] R6_2.2.0         highr_0.6       
 [7] stringr_1.2.0    tools_3.3.3     
 [9] DBI_0.6-1        htmltools_0.3.5 
[11] rprojroot_1.2    yaml_2.1.14     
[13] digest_0.6.12    assertthat_0.2.0
[15] tibble_1.3.0     RJSONIO_1.3-0   
[17] htmlwidgets_0.8  bitops_1.0-6    
[19] rsconnect_0.7    RCurl_1.95-4.8  
[21] curl_2.4         evaluate_0.10   
[23] mime_0.5         stringi_1.1.5   
[25] backports_1.0.5  httpuv_1.3.3    
```
