### ISSUE TITLE
Websocket Closing with Contour HTTP Proxy

### ISSUE THREAD

**Issue by jdonnell01** [rstudio/shiny#2925]
Hello,

I am trying to deploy my Shiny web app via Kubernetes and leverage the Contour HTTP Proxy (https://projectcontour.io/docs/master/httpproxy/) along with the Rocker R base image: https://hub.docker.com/r/rocker/r-base/. I have no issue connecting to my app via the web browser, however the web socket connection will sporadically close. I have enabled web sockets on the connection and set the timeout to infinity as dictated in the Project Contour docs, however the websocket connection will drop at anywhere from 10-20 minutes of using the app - even when not idle. Is there anything I can do in order to troublshoot? I have no logs to inspect outside of the message in the web browser console stating that the websocket closed: WebSocket connection to '<fqdn>' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

This is my HTTPProxy config:

```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
   name: simpleingress
spec:
      virtualhost:
         fqdn: <fqdn>
         tls:
            secretName: ingress-contour/ingress-contour-default-ssl-cert
     routes:
    - services:
        - name: simpleservice
          port: 8080
      loadBalancerPolicy:
        strategy: Cookie
      timeoutPolicy:
        response: infinity
        idle: infinity
    - conditions:
      - prefix: /websocket
      services:
        - name: simpleservice
          port: 8080
      enableWebsockets: true
      loadBalancerPolicy:
        strategy: Cookie
      timeoutPolicy:
        response: infinity
        idle: infinity
```

- Contour version: 1.3
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7"

> sessionInfo()
```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux bullseye/sid

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] rintrojs_0.2.2        aws.s3_0.3.12         purrr_0.3.3
 [4] dplyr_0.8.3           highcharter_0.7.0     XML_3.98-1.20
 [7] stringr_1.4.0         tidyjson_0.2.2        httr_1.4.1
[10] shinyjs_1.0           visNetwork_2.0.8      shinycssloaders_0.2.0
[13] DT_0.9                shinyBS_0.61          shinydashboard_0.7.1
[16] shiny_1.4.0

loaded via a namespace (and not attached):
 [1] zoo_1.8-7           tidyselect_0.2.5    lattice_0.20-41
 [4] generics_0.0.2      vctrs_0.2.1         htmltools_0.4.0
 [7] base64enc_0.1-3     yaml_2.2.0          rlang_0.4.2
[10] later_1.0.0         pillar_1.4.2        glue_1.3.1
[13] TTR_0.23-6          lifecycle_0.1.0     quantmod_0.4.17
[16] htmlwidgets_1.5.1   fastmap_1.0.1       httpuv_1.5.4
[19] curl_4.2            broom_0.5.4         xts_0.12-0
[22] Rcpp_1.0.3          xtable_1.8-4        promises_1.1.0
[25] backports_1.1.5     jsonlite_1.6        mime_0.7
[28] digest_0.6.23       stringi_1.4.3       rlist_0.4.6.1
[31] grid_3.6.1          tools_3.6.1         magrittr_1.5
[34] tibble_2.1.3        aws.signature_0.5.2 whisker_0.4
[37] crayon_1.3.4        tidyr_1.0.0         pkgconfig_2.0.3
[40] zeallot_0.1.0       xml2_1.2.2          data.table_1.12.6
[43] lubridate_1.7.8     assertthat_0.2.1    R6_2.4.1
[46] igraph_1.2.4.1      nlme_3.1-147        compiler_3.6.1
```
