### ISSUE TITLE
Progress with 'closeButton' option 

### ISSUE THREAD

**Issue by dipterix** [rstudio/shiny#2979]
How can I hide the little `x` in progress bar? Some of my users think by clicking `x`, they could interrupt current R, but it's just hiding the UI element.
![image](https://user-images.githubusercontent.com/8163576/88320251-ed0dc800-cce2-11ea-8049-4fd68f61ebbe.png)

**Comment by ColinFay** [comment]
You can add some CSS to hide it: 

```css
.shiny-notification-close {
    display: none;
}
```
