### ISSUE TITLE
Change default position of showNotification

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#2988]
Using these rules (in addition to what's being applied to `#shiny-notification-panel` already) puts notifications at the top-center of the page, where they are much more noticeable.

```css
/* Put shiny notifications front and center */
#shiny-notification-panel {
  top: 0;
  bottom: unset;
  left: 0;
  right: 0;
  margin-left: auto;
  margin-right: auto;
  width: 100%;
  max-width: 450px;
}
```
