### ISSUE TITLE
Embedded non-bslib shiny apps inherit styles from rmarkdown's bslib theme

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shiny#3299]
For example, notice how, in this document, the embedded app's sliders reflects the documents primary color

```r
remotes::install_github("rstudio/rmarkdown")
```

````yaml
---
title: "Real-time theming"
runtime: shiny
output: 
  html_document:
    theme:
      bg: "#121212"
      fg: "#E4E4E4"
      primary: "#EA80FC"
      secondary: "#00DAC6"
      base_font: !expr bslib::font_google("Open Sans")
      heading_font: !expr bslib::font_google("Proza Libre")
      code_font: !expr bslib::font_google("Fira Code")
      code-color: "#00DAC6"
---

```{r setup, include=FALSE}
bslib::bs_themer()
thematic::thematic_shiny(font = "auto")
```

This R Markdown document is made interactive using Shiny. Unlike the more traditional workflow of creating static reports, you can now create documents that allow your readers to change the assumptions underlying your analysis and see the results immediately. 

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

## Inputs and Outputs

You can embed Shiny inputs and outputs in your document. Outputs are automatically updated whenever inputs change.  This demonstrates how a standard R plot can be made interactive by wrapping it in the Shiny `renderPlot` function. The `selectInput` and `sliderInput` functions create the input widgets used to drive the plot.

```{r eruptions, echo=FALSE}
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)

renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```

## Embedded Application

It's also possible to embed an entire Shiny application within an R Markdown document using the `shinyAppDir` function. This example embeds a Shiny application located in another directory:

```{r tabsets, echo=FALSE}
shinyAppDir(
  system.file("examples/06_tabsets", package = "shiny"),
  options = list(
    width = "100%", height = 550
  )
)
```

Note the use of the `height` parameter to determine how much vertical space the embedded application should occupy.

You can also use the `shinyApp` function to define an application inline rather then in an external directory.

In all of R code chunks above the `echo = FALSE` attribute is used. This is to prevent the R code within the chunk from rendering in the document alongside the Shiny components.
````

<img width="1022" alt="Screen Shot 2021-02-18 at 11 03 12 AM" src="https://user-images.githubusercontent.com/1365941/108393086-ef80c380-71d8-11eb-9dde-b593cbacdfd3.png">
