### ISSUE TITLE
Namespace ionrangeslider Sass variables and map to CSS custom properties

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/shiny#3848]
Shiny provides styles and Sass variables to customize the `sliderInput()`, but they're scoped to a Sass block

https://github.com/rstudio/shiny/blob/b38a6302245c42a22bf1f356de188ff6cded8c5f/inst/www/shared/ionrangeslider/scss/shiny.scss#L27-L35

Unfortunately, it's not possible to scope variable overrides in Sass to the same selector used for the original scope. Instead, you have to set the default in the global namespace.

```scss
$fruit: apple !default;

.a {
  $fruit: banana !default;
  $veggie: carrot !default;
  --fruit: $fruit;         // apple
  --veggie: $veggie;       // carrot
}

.a {
  $fruit: mango;
  $veggie: asparagus;
  --fruit: $fruit;    // mango
  --veggie: $veggie;  // asparagus
}
```

Note that in the block above, the values of `$fruit` and `$veggie` in the first `.a` rule are completely independent of the same values in the second `.a` rule.

To improve this situation, we should:

1. Define the IRS variables in global scope with a prefix, e.g. `$irs-shiny-top`, `$irs-shiny-line-height`, etc.
2. Map these values to CSS variables that _are_ scoped in the `.irs--shiny` class. We'd then use those CSS variables wherever we currently use Sass variables so that the slider can be themed in the browser.
