### ISSUE TITLE
Should have nicer looking file input

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#760]
The default file input widget looks inconsistent across browsers, and they look especially bad on Chrome:
![image](https://cloud.githubusercontent.com/assets/86978/6536545/09a792a8-c414-11e4-82c4-f698d938e348.png)

We should use a nicer-looking input widget, like this:
http://gregpike.net/demos/bootstrap-file-input/demo.html

**Comment by thomasp85** [comment]
Have a look at the implementation I used in https://thomas.shinyapps.io/PanVizGenerator/

Basically the markup is like this:
```html
<div class="input-group fileinput">
    <input type="text" class="form-control" readonly>
    <span class="btn btn-default btn-file input-group-addon">
        <span class="glyphicon glyphicon-folder-open"></span>
        <input type="file">
    </span>
</div>
```

and the accompanying css like this:

```css
.btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
}
```

And some javascript to fill out the name of the selected file:

```javascript
$(document).on('fileselect', '.btn-file :file', function(event, numFiles, label) {
   var input = $(this).parents('.fileinput').find(':text');
   input.val(label);
});
```
(there should be some more logic to handle multiple file selections...)

This is obviously more involved than just replacing it with a bootstrap button, but I think it replicates the native idea but with more style...
